#!/bin/sh

ngrid=`cat nsprobnum | head -n 1 | sed "s/\([0-9]*\),\([0-9]*\)/\2/g"`
n=1
while [ $n -le $ngrid ]; do
	cat psimspecgraph002.m | sed "s/repng/$n/g" > graph$n.m
	matrunnm graph$n.m
	sleep 2s
	n=`expr $n + 1`
done

sleep 60s
psrem=`qstat | grep graph | grep -v ' dr '`
while [ ${#psrem} -gt 0 ]; do
	sleep 10s
	psrem=`qstat | grep graph | grep -v ' dr '`
done

rm graph*