#!/bin/sh

ngrid=`cat nsprobnum | head -n 1 | sed "s/\([0-9]*\),\([0-9]*\)/\2/g"`
n=1
while [ $n -le $ngrid ]; do
	if [ -f outmat/trans${n}.mat ]; then
		echo "trans${n}.mat exists"
	else
		cat PSimTrans002.m | sed "s/repng/$n/g" > Trans${n}.m
		matrunnm Trans${n}.m
		sleep 2s
	fi
	n=`expr $n + 1`
done
