#!/bin/sh

ngrid=`cat nsprobnum | head -n 1 | sed "s/\([0-9]*\),\([0-9]*\)/\2/g"`
n=1
command=matrun
flist=''
while [ $n -le $ngrid ]; do
	if [ ! -f outmat/pol$n.mat ]; then
		test1=`qstat | grep " VFTX${n} " | egrep ' r  |  qw ' | wc -l`
		if [ $test1 -eq 0 ]; then
			if [ -f VFTX${n}.txt ]; then
				rm VFTX${n}.txt
			fi
			cat PSimVF002.m | sed "s/repng/$n/g" > VFTX$n.m
			$command VFTX$n.m $@ >/dev/null
			echo "Running VFTX${n}"
			sleep 10.0s
		else
			echo "VFTX$n already running"
		fi
	else
		echo "VFTX${n} is already finished"
# 		mv VF${n}* outfiles
	fi
	n=`expr $n + 1`
done
sleep 10s

while [ `qstat | grep -i VFTX | wc -l` -gt 0 ]; do
	sleep 5m
done
rm VFTX*
