#!/bin/sh

command=matrun
if [ $# -ge 1 ]; then 
	opt=$@
fi 

simlist=`ls outmat/pol* | sed 's/.*pol\([0-9]*\).mat/\1/g'`
for sim in $simlist; do
	if [ ! -f outmat/pricesim${sim}$.mat ]; then 
		cat PSimPrices002.m | sed "s/repng/$sim/g" > Prices${sim}.m
		$command Prices${sim}.m $opt > /dev/null 
		sleep 0.5s
	else
		echo "Prices for simulation $sim already generated"
	fi 
done

while [ `qstat | grep Prices | wc -l` -gt 0 ]; do 
	sleep 30s 
done 

rm Prices* 

# ngrid=`cat nsprobnum | head -n 1 | sed "s/\([0-9]*\),\([0-9]*\)/\2/g"`
# n=1
# while [ $n -le $ngrid ]; do
# 	cat PSimPrices002.m | sed "s/repng/$n/g" > Price$n.m
# 	matrunnm Price$n.m
# 	sleep 2s
# 	n=`expr $n + 1`
# done



